(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(R-editor "ec")
 '(S-editor "ec")
 '(TeX-view-program-list (quote (("Skim" "/Applications/Skim.app/Contents/SharedSupport/displayline %n %o %b"))))
 '(TeX-view-program-selection (quote (((output-dvi style-pstricks) "dvips and gv") (output-dvi "xdvi") (output-pdf "Skim") (output-html "xdg-open"))))
 '(ansi-color-for-comint-mode t)
 '(aquamacs-additional-fontsets nil t)
 '(aquamacs-customization-version-id 300 t)
 '(aquamacs-tool-bar-user-customization nil t)
 '(auto-completion-source (quote dabbrev))
 '(blink-cursor-mode nil)
 '(comint-completion-autolist t)
 '(comint-move-point-for-output t)
 '(comint-scroll-show-maximum-output nil)
 '(comint-scroll-to-bottom-on-input t)
 '(completion-auto-show (quote completion-show-tooltip))
 '(cua-mode t nil (cua-base))
 '(debug-on-error nil)
 '(display-time-mode t)
 '(ecb-auto-activate t)
 '(ecb-clear-caches-before-activate t)
 '(ecb-compilation-buffer-names (quote (("*Kill Ring*") ("*Colors*") ("*Faces*") ("*Calculator*") ("*vc.**" . t) ("*magit.**" . t) ("*magit-.**" . t) ("*Apropos*") ("*Occur*") ("*shell*") ("*ansi-term*") ("*term.**" . t) ("\\*[cC]ompilation.*\\*" . t) ("\\*i?grep.*\\*" . t) ("*JDEE Compile Server*") ("*Completions*") ("*Backtrace*") ("*Compile-log*") ("*bsh*") ("*less*") ("*Messages*") ("*eshell*") ("*R*") ("*Ido Completions*") ("*ess-output*") ("*Shell.**" . t) ("*Tex Help*") ("Tex Live 2010") ("*Tex.**" . t) ("*ESS.*" . t) ("*Customize.**" . t) ("*[hH]elp.**" . t) ("*Process List*") ("widget-choose") ("*Ibuffer*") ("*Python.**" . t) ("*MATLAB*") ("*maxima*") ("*imaxima*") (".*Notes.org" . t) ("NOTES-.*.org" . t) ("*Packages*") ("*Disabled Command*") ("*Man.**" . t) ("*IPython.**" . t) ("*[aA]nything.**" . t) ("*Async Shell Command*"))))
 '(ecb-compile-window-height 0.25)
 '(ecb-compile-window-temporally-enlarge (quote both))
 '(ecb-compile-window-width (quote edit-window))
 '(ecb-directories-general-face (quote ecb-directories-general-face))
 '(ecb-directory-face (quote ecb-directory-face))
 '(ecb-eshell-auto-activate t)
 '(ecb-eshell-buffer-sync (quote always))
 '(ecb-eshell-buffer-sync-delay nil)
 '(ecb-excluded-directories-regexps (quote ("^\\(CVS\\|\\.[^xX]*\\)$" "^\\..*$" "^Applications$" "^Dropbox$" "^Mail$" "^Pictures$" "^Movies$" "^Music$" "^Downloads$")))
 '(ecb-layout-name "left13")
 '(ecb-layout-window-sizes (quote (("left2" (0.15469613259668508 . 0.6511627906976745) (0.15469613259668508 . 0.6511627906976745)) ("left13" (0.18232044198895028 . 1.302325581395349)) ("left9" (0.11049723756906077 . 1.302325581395349)) ("left14" (0.17796610169491525 . 0.9642857142857143) (0.17796610169491525 . 0.32142857142857145)) ("left6" (0.19337016574585636 . 0.4418604651162791) (0.19337016574585636 . 0.5116279069767442) (0.19337016574585636 . 0.3488372093023256)) ("left8" (0.14917127071823205 . 0.2807017543859649) (0.14917127071823205 . 0.24561403508771928) (0.14917127071823205 . 0.2807017543859649) (0.14917127071823205 . 0.17543859649122806)) ("left-analyse" (0.24581005586592178 . 0.2807017543859649) (0.24581005586592178 . 0.24561403508771928) (0.24581005586592178 . 0.22807017543859648) (0.24581005586592178 . 0.22807017543859648)))))
 '(ecb-major-modes-show-or-hide (quote (nil ESS Latex)))
 '(ecb-options-version "2.40")
 '(ecb-other-window-behavior (quote all))
 '(ecb-select-edit-window-on-redraw nil)
 '(ecb-source-file-regexps (quote ((".*" ("\\(^\\(\\.\\|#\\)\\|\\(~$\\|\\.\\(elc\\|obj\\|o\\|class\\|lib\\|dll\\|a\\|so\\|cache\\|dat\\|orig\\|pdf\\|aux\\|eps\\|log\\|dvi\\|dylib\\)$\\)\\)") ("^\\.\\(emacs\\|gnus\\)$")))))
 '(ecb-source-path (quote (("/Users/dkr/.emacs.d" "Emacs Config") ("/Users/dkr/Research/Code/ArcticLake" "Arctic Lake") ("/Users/dkr/Research/Code/Regime" "Regime") ("/Users/dkr/Code/ml/MLBook/Code/src" "ML Book") ("/Users/dkr/Research/Essays" "Essays") ("/Users/dkr/Research/Code/MATLAB/Functional_Data_Analysis/examples" "FDA Examples") ("/Users/dkr/Code/fda/R/demo" "FDA Demo") ("/Users/dkr/Library/R/2.12/library/fda/scripts" "FDA Scripts") ("/Users/dkr/Code/fda/R/R" "FDA") ("/Users/dkr/Code/scala/examples" "ProInScala") ("/Users/dkr/Research/Code/ArcticLakeProduction" "AL Production"))))
 '(ecb-sources-general-face (quote ecb-sources-general-face))
 '(ecb-tip-of-the-day nil)
 '(ecb-tree-buffer-style (quote ascii-guides))
 '(ecb-tree-indent 2)
 '(ecb-use-speedbar-instead-native-tree-buffer nil)
 '(ecb-windows-height 0.25)
 '(ecb-windows-width 0.25)
 '(eshell-cmpl-cycle-completions nil)
 '(eshell-scroll-to-bottom-on-output this)
 '(ess-help-kill-bogus-buffers t)
 '(ess-history-file ".Rhistory")
 '(ess-tab-always-indent nil)
 '(g-user-email "dongkeren@gmail.com")
 '(gnus-default-directory "~/.gnus.d")
 '(ibuffer-show-empty-filter-groups nil t)
 '(ido-completion-buffer-all-completions nil)
 '(ido-create-new-buffer (quote never))
 '(ido-enable-flex-matching t)
 '(ido-ignore-buffers (quote ("\\` " "*.**")))
 '(ido-ignore-directories (quote ("\\`CVS/" "\\`\\.\\./" "\\`\\./")))
 '(ido-max-prospects 5)
 '(ido-mode (quote both) nil (ido))
 '(imaxima-bg-color "dark slate gray")
 '(imaxima-equation-color "wheat")
 '(imaxima-fg-color "wheat")
 '(imaxima-fnt-size "huge")
 '(imaxima-label-color "coral")
 '(imaxima-scale-factor 1.0)
 '(imaxima-use-maxima-mode-flag t)
 '(indicate-empty-lines nil)
 '(ipython-command "/usr/local/bin/ipython")
 '(ns-alternate-modifier (quote alt))
 '(ns-pop-up-frames nil)
 '(ns-tool-bar-display-mode (quote both) t)
 '(ns-tool-bar-size-mode (quote regular) t)
 '(org-capture-templates (quote (("t" "Targets" entry (file "NOTES-targets.org") "* TODO %?\\n  %i\\n  %a" :prepend t :clock-in t :unnarrowed t :kill-buffer t) ("i" "Tips" entry (file "NOTES-tips.org") "" :clock-in t :unnarrowed t) ("j" "Journal" entry (file "NOTES-journal.org") "* %?\\\\nEntered on %U\\\\n  %i\\\\n  %a" :prepend t :kill-buffer t))))
 '(org-completion-use-ido t)
 '(org-default-notes-file "~/Dropbox/Documents/ORG/notes.org")
 '(org-directory "~/Dropbox/Documents/ORG")
 '(package-archives (quote (("original" . "http://tromey.com/elpa/") ("gnu" . "http://elpa.gnu.org/packages/") ("technomancy" . "http://repo.technomancy.us/emacs/") ("kjhealy" . "http://kieranhealy.org/packages/"))))
 '(py-python-command "/usr/local/bin/ipython")
 '(py-python-command-args (quote ("-pylab" "tk" "--colors" "Linux" "--no-banner")))
 '(python-python-command "python")
 '(remember-data-file "~/Dropbox/Documents/ORG/notes.org")
 '(scroll-bar-mode nil)
 '(scroll-preserve-screen-position nil)
 '(show-paren-mode t)
 '(sql-mysql-login-params (quote (user password database server)))
 '(sql-password "")
 '(tab-width 4)
 '(term-bind-key-alist (quote (("C-c C-c" . term-interrupt-subjob) ("C-c C-j" . term-line-mode) ("C-c C-k" . term-char-mode) ("C-p" . previous-line) ("C-n" . next-line) ("C-s" . isearch-forward) ("C-r" . isearch-backward) ("C-m" . term-send-raw) ("M-f" . term-send-forward-word) ("M-b" . term-send-backward-word) ("M-o" . term-send-backspace) ("C-h" . term-send-backspace) ("M-p" . term-send-up) ("M-n" . term-send-down) ("M-M" . term-send-forward-kill-word) ("M-N" . term-send-backward-kill-word) ("C-<backspace>" . term-send-backward-kill-word) ("M-r" . term-send-reverse-search-history) ("M-s" . term-send-reverse-search-history) ("M-," . term-send-input) ("<M-backspace>" . term-send-raw-meta) ("M-." . comint-dynamic-complete) ("C-<left>" . term-send-backward-word) ("C-<right>" . term-send-forward-word))))
 '(term-buffer-maximum-size 262144)
 '(term-default-bg-color "dark slate gray")
 '(term-default-fg-color "wheat")
 '(text-mode-hook (quote (text-mode-hook-identify)))
 '(tool-bar-mode nil)
 '(visible-cursor t)
 '(visual-line-mode nil t)
 '(winring-prompt-on-create nil)
 '(winring-show-names t)
 '(woman-manpath (quote ("/usr/share/man" "/usr/local/share/man" "/usr/X11/man" ("/bin" . "/usr/share/man") ("/sbin" . "/usr/share/man") ("/usr/bin" . "/usr/share/man") ("/usr/sbin" . "/usr/share/man") ("/usr/local/bin" . "/usr/local/share/man") ("/usr/local/sbin" . "/usr/local/share/man") ("/usr/X11/bin" . "/usr/X11/man") ("/usr/bin/X11" . "/usr/X11/man") ("/usr/bin/mh" . "/usr/share/man") ("/opt/local/bin" . "/opt/local/share/man"))))
 '(woman-path (quote ("/opt/local/share/man")))
 '(x-stretch-cursor t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ecb-directories-general-face ((t (:inherit ecb-default-general-face :family "Consolas"))))
 '(ecb-source-face ((t (:inherit (ecb-sources-general-face ecb-default-highlight-face) :background "magenta"))))
 '(ecb-source-in-directories-buffer-face ((t (:inherit ecb-directories-general-face :foreground "pale green" :slant italic))))
 '(ecb-source-read-only-face ((t (:inherit ecb-default-general-face :foreground "orange red" :slant italic))))
 '(ecb-sources-general-face ((t (:inherit ecb-default-general-face :foreground "pale green" :family "Lucida Sans"))))
 '(fixed-pitch ((default nil) (nil nil)))
 '(font-lock-function-name-face ((t (:foreground "aquamarine" :weight bold :height 1))))
 '(ido-subdir ((t (:foreground "coral1"))))
 '(imaxima-latex-error-face ((t (:foreground "dark turquoise" :underline t)))))
